version: "2"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf:ro'
    links:
      - "wordpress"
    volumes_from:
      - "wordpress:ro"
    environment:
      NGINX_PORT: "8080"

  wordpress-db:
    image: mariadb
    volumes:
      - './data/wordpress/db:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: '${WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${WORDPRESS_MYSQL_PASSWORD}'

  wordpress:
    image: ellakcy/wordpressswithplugins:alpine-fpm
    links:
      - wordpress-db
    volumes:
        - './data/wordpress/www:/var/www/html'
    environment:
        WORDPRESS_DB_HOST: wordpress-db:/var/run/mysqld/mysqld.sock
        WORDPRESS_DB_USER: '${WORDPRESS_MYSQL_USER}'
        WORDPRESS_DB_PASSWORD: '${WORDPRESS_MYSQL_PASSWORD}'
        WORDPRESS_ADMIN_USERNAME: '${WORDPRESS_ADMIN_USER}'
        WORDPRESS_ADMIN_PASSWORD: '${WORDPRESS_ADMIN_PASSWORD}'
        WORDPRESS_URL: '${WORDPRESS_URL}'
